### ISSUE TITLE
Softwaredesign Ansteuerung

### ISSUE THREAD

**Issue by GetDautz** [adrianmoerk/RoboChess#12]
## Diskussion/Meeting:
_Nutzt die Kommentar-Funktion für Vorschläge und Ideen._  
  
**27.09.2023** - Besprechung Softwaredesign
- Webserver von der Arbeit wiederverwenden
- WebSockets zwischen Frontend und Backend

## TODO
 - [ ] UML-Ablaufdiagramm für Version 1.0 erstellen
 - [ ] UML-Ablaufdiagramm für Version 1.1 erstellen
 - [ ] UML-Ablaufdiagramm für Version 1.2 erstellen
